apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      name: todo-app-pod
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: prakhards98/todo-app
          ports:
            - containerPort: 80
